### ISSUE TITLE
Error: Could not open stream: Internal PortAudio error

### ISSUE THREAD

**Issue by zhangxiann** [pervasive-systems/eSense-Data-Visualiser#2]
[2019-08-28T16:53:23.523] [INFO] [eSense-Recorder] - socket client 4sJNLW0-0PooeGxuAAAB is connected
||PaMacCore (AUHAL)|| Error on line 2490: err='-50', msg=Unknown Error
[2019-08-28T16:55:57.496] [INFO] [eSense-Recorder] - socket client 4sJNLW0-0PooeGxuAAAB is disconnected
[2019-08-28T16:55:57.601] [INFO] [eSense-Recorder] - socket client I_WvbJDmuZC_zJsXAAAC is connected
[2019-08-28T16:57:01.243] [INFO] [eSense-Recorder] - Trying to connect
Input audio options: default device, sample rate 16000, channels 1, bits per sample 16, max queue 2
Input device name is eSense-1403
||PaMacCore (AUHAL)|| Warning on line 520: err=''!dev'', msg=Audio Hardware: Bad Device
||PaMacCore (AUHAL)|| Warning on line 440: err=''!dev'', msg=Audio Hardware: Bad Device
||PaMacCore (AUHAL)|| Error on line 1306: err='-10851', msg=Audio Unit: Invalid Property Value
/Users/zhangxian/Desktop/eSense/eSense-Data-Visualiser/node_modules/naudiodon/index.js:35
  this.AudioInAdon = new portAudioBindings.AudioIn(options);
                     ^

Error: Could not open stream: Internal PortAudio error
    at new AudioInput (/Users/zhangxian/Desktop/eSense/eSense-Data-Visualiser/node_modules/naudiodon/index.js:35:22)
    at createAudioInput (/Users/zhangxian/Desktop/eSense/eSense-Data-Visualiser/index.js:501:11)
    at Socket.<anonymous> (/Users/zhangxian/Desktop/eSense/eSense-Data-Visualiser/index.js:80:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /Users/zhangxian/Desktop/eSense/eSense-Data-Visualiser/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

![image](https://user-images.githubusercontent.com/12131262/63841411-5727cb00-c9b5-11e9-8ce0-aaca9eb98958.png)

**Comment by alessandro-montanari** [comment]
Let me know which OS are you using and versions of node and npm so we can try to reproduce the error.

**Comment by zhangxiann** [comment]
the OS is macOS High Sierra(10.13.3), and the node version is v8.16.1

**Comment by alessandro-montanari** [comment]
We have tested the app on macOS Mojave. I wondering if that's the problem. Do you get any error or warning when installing the app with `npm install`?
